language: php

php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - hhvm

sudo: false

before_install:
  - composer self-update

install:
  - composer install --prefer-dist --no-interaction

script:
  - vendor/bin/phpunit
